[2025-02-14T07:15:03.995+0000] {processor.py:154} INFO - Started process (PID=63) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:15:03.999+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:15:04.001+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:15:04.001+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:15:04.073+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:15:04.225+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:15:04.225+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:15:04.379+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:15:04.379+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:15:04.506+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.519 seconds
[2025-02-14T07:15:35.233+0000] {processor.py:154} INFO - Started process (PID=92) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:15:35.235+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:15:35.237+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:15:35.236+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:15:35.278+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:15:35.362+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:15:35.361+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:15:35.410+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:15:35.410+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:15:35.456+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.228 seconds
[2025-02-14T07:16:05.808+0000] {processor.py:154} INFO - Started process (PID=123) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:16:05.810+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:16:05.811+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:16:05.811+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:16:05.857+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:16:05.949+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:16:05.949+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:16:06.007+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:16:06.007+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:16:06.060+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.259 seconds
[2025-02-14T07:16:36.322+0000] {processor.py:154} INFO - Started process (PID=153) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:16:36.324+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:16:36.325+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:16:36.325+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:16:36.362+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:16:36.432+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:16:36.431+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:16:36.478+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:16:36.478+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:16:36.520+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.203 seconds
[2025-02-14T07:17:06.782+0000] {processor.py:154} INFO - Started process (PID=193) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:17:06.784+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:17:06.786+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:17:06.785+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:17:06.826+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:17:06.918+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:17:06.918+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:17:06.983+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:17:06.983+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:17:07.039+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.264 seconds
[2025-02-14T07:17:37.340+0000] {processor.py:154} INFO - Started process (PID=221) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:17:37.342+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:17:37.343+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:17:37.343+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:17:37.380+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:17:37.447+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:17:37.447+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:17:37.499+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:17:37.499+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:17:37.539+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.204 seconds
[2025-02-14T07:18:08.132+0000] {processor.py:154} INFO - Started process (PID=260) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:18:08.134+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:18:08.136+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:18:08.135+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:18:08.184+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:18:08.266+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:18:08.265+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:18:08.307+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:18:08.306+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:18:08.344+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.217 seconds
[2025-02-14T07:19:03.587+0000] {processor.py:154} INFO - Started process (PID=63) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:19:03.591+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:19:03.595+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:19:03.595+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:19:03.679+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:19:04.015+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:19:04.014+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:19:04.127+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:19:04.126+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:19:04.241+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.665 seconds
[2025-02-14T07:19:35.003+0000] {processor.py:154} INFO - Started process (PID=92) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:19:35.005+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:19:35.007+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:19:35.007+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:19:35.043+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:19:35.115+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:19:35.114+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:19:35.167+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:19:35.167+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:19:35.265+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.267 seconds
[2025-02-14T07:20:05.381+0000] {processor.py:154} INFO - Started process (PID=133) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:20:05.383+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:20:05.385+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:20:05.385+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:20:05.426+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:20:05.496+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:20:05.496+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:20:05.542+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:20:05.541+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:20:05.580+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.204 seconds
[2025-02-14T07:20:36.299+0000] {processor.py:154} INFO - Started process (PID=163) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:20:36.302+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:20:36.305+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:20:36.305+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:20:36.351+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:20:36.433+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:20:36.433+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:20:36.479+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:20:36.479+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:20:36.524+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.232 seconds
[2025-02-14T07:21:07.136+0000] {processor.py:154} INFO - Started process (PID=201) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:21:07.139+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:21:07.142+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:21:07.142+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:21:07.197+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:21:07.282+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:21:07.281+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:21:07.332+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:21:07.332+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:21:07.382+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.311 seconds
[2025-02-14T07:21:37.734+0000] {processor.py:154} INFO - Started process (PID=231) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:21:37.737+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:21:37.739+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:21:37.739+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:21:37.785+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:21:37.880+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:21:37.880+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:21:37.954+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:21:37.953+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:21:37.998+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.272 seconds
[2025-02-14T07:22:08.050+0000] {processor.py:154} INFO - Started process (PID=262) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:22:08.052+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:22:08.055+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:22:08.055+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:22:08.096+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:22:08.183+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:22:08.182+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:22:08.229+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:22:08.228+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:22:08.274+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.230 seconds
[2025-02-14T07:22:38.875+0000] {processor.py:154} INFO - Started process (PID=300) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:22:38.879+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:22:38.882+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:22:38.882+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:22:38.948+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:22:39.071+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:22:39.070+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:22:39.145+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:22:39.144+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:22:39.214+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.346 seconds
[2025-02-14T07:23:09.457+0000] {processor.py:154} INFO - Started process (PID=332) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:23:09.460+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:23:09.462+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:23:09.462+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:23:09.506+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:23:09.599+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:23:09.598+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:23:09.647+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:23:09.647+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:23:09.696+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.249 seconds
[2025-02-14T07:23:40.029+0000] {processor.py:154} INFO - Started process (PID=371) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:23:40.034+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:23:40.038+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:23:40.037+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:23:40.115+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:23:40.234+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:23:40.234+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:23:40.341+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:23:40.341+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:23:40.412+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.396 seconds
[2025-02-14T07:24:10.665+0000] {processor.py:154} INFO - Started process (PID=401) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:24:10.705+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:24:10.709+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:24:10.709+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:24:10.907+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:24:11.027+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:24:11.026+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:24:11.146+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:24:11.146+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:24:11.258+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.598 seconds
[2025-02-14T07:24:41.920+0000] {processor.py:154} INFO - Started process (PID=432) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:24:41.924+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:24:41.928+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:24:41.927+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:24:41.974+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:24:42.057+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:24:42.056+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:24:42.124+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:24:42.124+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:24:42.175+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.260 seconds
[2025-02-14T07:25:12.821+0000] {processor.py:154} INFO - Started process (PID=469) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:25:12.824+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:25:12.828+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:25:12.828+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:25:12.873+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:25:12.971+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:25:12.971+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:25:13.021+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:25:13.021+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:25:13.062+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.249 seconds
[2025-02-14T07:25:43.795+0000] {processor.py:154} INFO - Started process (PID=502) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:25:43.801+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:25:43.809+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:25:43.808+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:25:43.874+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:25:44.015+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:25:44.015+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:25:44.099+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:25:44.099+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:25:44.212+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.431 seconds
[2025-02-14T07:26:14.336+0000] {processor.py:154} INFO - Started process (PID=532) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:26:14.339+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:26:14.341+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:26:14.341+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:26:14.385+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:26:14.468+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:26:14.468+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:26:14.527+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:26:14.527+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:26:14.573+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.243 seconds
[2025-02-14T07:26:44.654+0000] {processor.py:154} INFO - Started process (PID=569) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:26:44.667+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:26:44.674+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:26:44.673+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:26:44.850+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:26:45.007+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:26:45.006+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:26:45.124+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:26:45.124+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:26:45.247+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.605 seconds
[2025-02-14T07:27:15.759+0000] {processor.py:154} INFO - Started process (PID=600) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:27:15.762+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:27:15.764+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:27:15.764+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:27:15.815+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:27:15.892+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:27:15.891+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:27:15.939+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:27:15.938+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:27:15.980+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.228 seconds
[2025-02-14T07:27:46.699+0000] {processor.py:154} INFO - Started process (PID=630) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:27:46.703+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:27:46.705+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:27:46.705+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:27:46.769+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:27:46.867+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:27:46.867+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:27:46.927+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:27:46.927+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:27:46.969+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.279 seconds
[2025-02-14T07:28:17.163+0000] {processor.py:154} INFO - Started process (PID=669) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:28:17.166+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:28:17.169+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:28:17.169+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:28:17.220+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:28:17.291+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:28:17.290+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:28:17.336+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:28:17.336+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:28:17.377+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.221 seconds
[2025-02-14T07:28:47.475+0000] {processor.py:154} INFO - Started process (PID=699) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:28:47.478+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:28:47.480+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:28:47.480+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:28:47.517+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:28:47.588+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:28:47.588+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:28:47.632+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:28:47.632+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:28:47.674+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.206 seconds
[2025-02-14T07:29:18.022+0000] {processor.py:154} INFO - Started process (PID=737) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:29:18.025+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:29:18.028+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:29:18.028+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:29:18.096+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:29:18.235+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:29:18.233+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:29:18.309+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:29:18.309+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:29:18.361+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.347 seconds
[2025-02-14T07:29:48.459+0000] {processor.py:154} INFO - Started process (PID=767) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:29:48.463+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:29:48.469+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:29:48.468+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:29:48.511+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:29:48.588+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:29:48.588+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:29:48.637+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:29:48.637+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:29:48.688+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.234 seconds
[2025-02-14T07:30:18.803+0000] {processor.py:154} INFO - Started process (PID=798) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:30:18.805+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:30:18.808+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:30:18.808+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:30:18.848+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:30:18.918+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:30:18.917+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:30:18.966+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:30:18.966+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:30:19.008+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.211 seconds
[2025-02-14T07:30:49.241+0000] {processor.py:154} INFO - Started process (PID=837) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:30:49.244+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:30:49.247+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:30:49.247+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:30:49.300+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:30:49.402+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:30:49.402+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:30:49.469+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:30:49.469+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:30:49.534+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.300 seconds
[2025-02-14T07:31:20.304+0000] {processor.py:154} INFO - Started process (PID=867) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:31:20.307+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:31:20.309+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:31:20.309+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:31:20.349+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:31:20.425+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:31:20.424+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:31:20.474+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:31:20.474+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:31:20.523+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.224 seconds
[2025-02-14T07:31:50.941+0000] {processor.py:154} INFO - Started process (PID=906) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:31:50.944+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:31:50.946+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:31:50.946+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:31:50.982+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:31:51.054+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:31:51.053+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:31:51.096+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:31:51.096+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:31:51.147+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.211 seconds
[2025-02-14T07:32:21.351+0000] {processor.py:154} INFO - Started process (PID=936) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:32:21.354+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:32:21.357+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:32:21.357+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:32:21.402+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:32:21.472+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:32:21.472+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:32:21.514+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:32:21.514+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:32:21.558+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.212 seconds
[2025-02-14T07:32:51.674+0000] {processor.py:154} INFO - Started process (PID=975) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:32:51.682+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:32:51.685+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:32:51.685+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:32:51.754+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:32:51.856+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:32:51.856+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:32:51.917+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:32:51.917+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:32:52.002+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.336 seconds
[2025-02-14T07:33:22.052+0000] {processor.py:154} INFO - Started process (PID=1005) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:33:22.055+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:33:22.058+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:33:22.057+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:33:22.111+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:33:22.189+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:33:22.188+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:33:22.244+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:33:22.243+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:33:22.292+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.246 seconds
[2025-02-14T07:33:52.494+0000] {processor.py:154} INFO - Started process (PID=1035) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:33:52.498+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:33:52.502+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:33:52.501+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:33:52.563+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:33:52.660+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:33:52.659+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:33:52.720+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:33:52.720+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:33:52.781+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.292 seconds
[2025-02-14T07:34:24.277+0000] {processor.py:154} INFO - Started process (PID=1075) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:34:24.280+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:34:24.282+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:24.281+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:34:24.322+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:34:24.395+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:24.394+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:34:24.441+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:24.441+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:34:24.483+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.211 seconds
[2025-02-14T07:34:55.130+0000] {processor.py:154} INFO - Started process (PID=1114) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:34:55.134+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:34:55.140+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:55.140+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:34:55.266+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:34:55.388+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:55.387+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:34:55.529+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:55.529+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:34:55.582+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.461 seconds
[2025-02-14T07:35:25.716+0000] {processor.py:154} INFO - Started process (PID=1145) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:35:25.719+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:35:25.722+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:25.722+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:35:25.766+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:35:25.838+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:25.837+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:35:25.881+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:25.881+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:35:25.921+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.211 seconds
[2025-02-14T07:35:55.997+0000] {processor.py:154} INFO - Started process (PID=1177) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:35:56.000+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:35:56.002+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:56.001+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:35:56.042+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:35:56.125+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:56.124+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:35:56.170+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:56.169+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:35:56.234+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.243 seconds
[2025-02-14T07:36:26.840+0000] {processor.py:154} INFO - Started process (PID=1216) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:36:26.843+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:36:26.846+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:26.846+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:36:26.898+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:36:26.987+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:26.987+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:36:27.052+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:27.051+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:36:27.101+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.270 seconds
[2025-02-14T07:36:57.405+0000] {processor.py:154} INFO - Started process (PID=1248) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:36:57.408+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:36:57.410+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:57.410+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:36:57.471+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:36:57.550+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:57.550+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:36:57.596+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:57.595+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:36:57.637+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.238 seconds
[2025-02-14T07:37:27.908+0000] {processor.py:154} INFO - Started process (PID=1286) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:37:27.912+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:37:27.914+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:27.914+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:37:27.955+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:37:28.038+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:28.038+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:37:28.099+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:28.099+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2025-02-14T07:37:28.149+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.247 seconds
[2025-02-14T07:37:51.409+0000] {processor.py:154} INFO - Started process (PID=1304) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:37:51.413+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:37:51.416+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:51.415+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:37:51.548+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:51.538+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:37:51.553+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:37:51.659+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.262 seconds
[2025-02-14T07:38:22.102+0000] {processor.py:154} INFO - Started process (PID=1345) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:38:22.107+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:38:22.109+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:22.109+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:38:22.160+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:22.155+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:38:22.162+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:38:22.242+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.149 seconds
[2025-02-14T07:38:52.624+0000] {processor.py:154} INFO - Started process (PID=1376) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:38:52.629+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:38:52.632+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:52.632+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:38:52.668+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:52.663+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:38:52.670+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:38:52.713+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.098 seconds
[2025-02-14T07:39:22.867+0000] {processor.py:154} INFO - Started process (PID=1407) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:39:22.870+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:39:22.872+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:39:22.872+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:39:22.911+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:39:22.908+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:39:22.913+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:39:23.011+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.153 seconds
[2025-02-14T07:39:53.655+0000] {processor.py:154} INFO - Started process (PID=1447) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:39:53.658+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:39:53.663+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:39:53.663+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:39:53.704+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:39:53.701+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:39:53.706+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:39:53.752+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.104 seconds
[2025-02-14T07:40:24.053+0000] {processor.py:154} INFO - Started process (PID=1478) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:40:24.060+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:40:24.064+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:40:24.063+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:40:24.115+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:40:24.110+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:40:24.117+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:40:24.159+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.114 seconds
[2025-02-14T07:40:54.482+0000] {processor.py:154} INFO - Started process (PID=1518) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:40:54.485+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:40:54.488+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:40:54.488+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:40:54.533+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:40:54.530+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:40:54.535+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:40:54.583+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.108 seconds
[2025-02-14T07:41:24.623+0000] {processor.py:154} INFO - Started process (PID=1550) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:41:24.626+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:41:24.629+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:41:24.628+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:41:24.672+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:41:24.668+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:41:24.674+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:41:24.727+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.115 seconds
[2025-02-14T07:41:55.319+0000] {processor.py:154} INFO - Started process (PID=1581) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:41:55.326+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:41:55.331+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:41:55.330+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:41:55.390+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:41:55.384+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:41:55.397+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:41:55.467+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.160 seconds
[2025-02-14T07:42:25.671+0000] {processor.py:154} INFO - Started process (PID=1621) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:42:25.674+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:42:25.679+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:42:25.678+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:42:25.718+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:42:25.713+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:42:25.720+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:42:25.759+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.094 seconds
[2025-02-14T07:42:56.276+0000] {processor.py:154} INFO - Started process (PID=1650) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:42:56.281+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:42:56.286+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:42:56.286+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:42:56.329+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:42:56.326+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:42:56.334+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:42:56.376+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.110 seconds
[2025-02-14T07:43:27.015+0000] {processor.py:154} INFO - Started process (PID=1690) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:43:27.018+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:43:27.020+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:43:27.020+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:43:27.060+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:43:27.056+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:43:27.064+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:43:27.110+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.102 seconds
[2025-02-14T07:43:57.212+0000] {processor.py:154} INFO - Started process (PID=1722) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:43:57.214+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:43:57.217+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:43:57.216+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:43:57.247+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:43:57.243+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:43:57.249+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:43:57.283+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.077 seconds
[2025-02-14T07:44:27.779+0000] {processor.py:154} INFO - Started process (PID=1759) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:44:27.782+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:44:27.784+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:44:27.784+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:44:27.830+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:44:27.826+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:44:27.832+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:44:27.872+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.101 seconds
[2025-02-14T07:44:58.288+0000] {processor.py:154} INFO - Started process (PID=1792) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:44:58.294+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:44:58.297+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:44:58.297+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:44:58.331+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:44:58.327+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:44:58.334+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:44:58.367+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.084 seconds
[2025-02-14T07:45:29.036+0000] {processor.py:154} INFO - Started process (PID=1830) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:45:29.040+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:45:29.043+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:45:29.043+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:45:29.102+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:45:29.096+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:45:29.106+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:45:29.165+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.139 seconds
[2025-02-14T07:45:59.847+0000] {processor.py:154} INFO - Started process (PID=1862) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:45:59.855+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:45:59.858+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:45:59.858+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:45:59.920+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:45:59.913+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:45:59.922+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:45:59.994+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.154 seconds
[2025-02-14T07:46:30.039+0000] {processor.py:154} INFO - Started process (PID=1893) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:46:30.042+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:46:30.044+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:46:30.044+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:46:30.089+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:46:30.085+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:46:30.091+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:46:30.134+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.101 seconds
[2025-02-14T07:47:00.830+0000] {processor.py:154} INFO - Started process (PID=1933) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:47:00.833+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:47:00.835+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:47:00.835+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:47:00.871+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:47:00.868+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:47:00.873+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:47:00.915+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.091 seconds
[2025-02-14T07:47:31.521+0000] {processor.py:154} INFO - Started process (PID=1963) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:47:31.524+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:47:31.527+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:47:31.527+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:47:31.567+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:47:31.563+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:47:31.569+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:47:31.628+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.113 seconds
[2025-02-14T07:48:02.139+0000] {processor.py:154} INFO - Started process (PID=2003) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:48:02.142+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:48:02.144+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:48:02.144+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:48:02.178+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:48:02.176+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:48:02.180+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:48:02.222+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.092 seconds
[2025-02-14T07:48:32.743+0000] {processor.py:154} INFO - Started process (PID=2034) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:48:32.747+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:48:32.751+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:48:32.750+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:48:32.792+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:48:32.787+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:48:32.794+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:48:32.931+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.196 seconds
[2025-02-14T07:49:03.005+0000] {processor.py:154} INFO - Started process (PID=2074) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:49:03.009+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:49:03.011+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:49:03.011+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:49:03.047+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:49:03.043+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:49:03.049+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:49:03.086+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.086 seconds
[2025-02-14T07:49:33.651+0000] {processor.py:154} INFO - Started process (PID=2104) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:49:33.654+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:49:33.656+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:49:33.656+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:49:33.698+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:49:33.694+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:49:33.700+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:49:33.738+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.094 seconds
[2025-02-14T07:50:03.966+0000] {processor.py:154} INFO - Started process (PID=2144) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:50:03.969+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:50:03.972+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:50:03.971+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:50:04.007+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:50:04.004+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:50:04.011+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:50:04.049+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.089 seconds
[2025-02-14T07:50:34.182+0000] {processor.py:154} INFO - Started process (PID=2175) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:50:34.186+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:50:34.189+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:50:34.188+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:50:34.222+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:50:34.218+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:50:34.224+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:50:34.259+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.082 seconds
[2025-02-14T07:51:04.551+0000] {processor.py:154} INFO - Started process (PID=2205) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:51:04.555+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:51:04.557+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:51:04.557+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:51:04.604+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:51:04.601+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:51:04.607+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:51:04.646+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.103 seconds
[2025-02-14T07:51:34.933+0000] {processor.py:154} INFO - Started process (PID=2245) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:51:34.936+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:51:34.938+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:51:34.938+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:51:34.972+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:51:34.969+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:51:34.975+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:51:35.008+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.081 seconds
[2025-02-14T07:52:05.756+0000] {processor.py:154} INFO - Started process (PID=2276) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:52:05.758+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:52:05.760+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:52:05.760+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:52:05.797+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:52:05.794+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:52:05.799+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:52:05.836+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.086 seconds
[2025-02-14T07:52:36.249+0000] {processor.py:154} INFO - Started process (PID=2316) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:52:36.251+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:52:36.254+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:52:36.254+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:52:36.294+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:52:36.291+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:52:36.296+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:52:36.335+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.094 seconds
[2025-02-14T07:53:06.863+0000] {processor.py:154} INFO - Started process (PID=2347) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:53:06.866+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:53:06.870+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:53:06.870+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:53:06.904+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:53:06.901+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:53:06.907+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:53:06.942+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.085 seconds
[2025-02-14T07:53:37.183+0000] {processor.py:154} INFO - Started process (PID=2387) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:53:37.186+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:53:37.189+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:53:37.189+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:53:37.224+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:53:37.221+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:53:37.226+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:53:37.266+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.089 seconds
[2025-02-14T07:54:07.665+0000] {processor.py:154} INFO - Started process (PID=2418) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:54:07.670+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:54:07.673+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:54:07.673+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:54:07.755+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:54:07.751+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:54:07.758+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:54:07.814+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.158 seconds
[2025-02-14T07:54:38.463+0000] {processor.py:154} INFO - Started process (PID=2457) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:54:38.465+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:54:38.467+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:54:38.467+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:54:38.500+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:54:38.498+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:54:38.503+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:54:38.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.084 seconds
[2025-02-14T07:55:08.860+0000] {processor.py:154} INFO - Started process (PID=2488) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:55:08.864+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:55:08.866+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:55:08.866+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:55:08.912+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:55:08.906+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:55:08.914+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:55:08.963+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.114 seconds
[2025-02-14T07:55:39.187+0000] {processor.py:154} INFO - Started process (PID=2527) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:55:39.192+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:55:39.195+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:55:39.194+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:55:39.235+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:55:39.232+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:55:39.237+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:55:39.278+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.098 seconds
[2025-02-14T07:56:09.542+0000] {processor.py:154} INFO - Started process (PID=2558) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:56:09.547+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:56:09.549+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:56:09.549+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:56:09.671+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:56:09.666+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:56:09.673+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:56:09.713+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.182 seconds
[2025-02-14T07:56:40.471+0000] {processor.py:154} INFO - Started process (PID=2598) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:56:40.475+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:56:40.480+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:56:40.479+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:56:40.525+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:56:40.521+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:56:40.527+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:56:40.571+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.112 seconds
[2025-02-14T07:57:11.236+0000] {processor.py:154} INFO - Started process (PID=2629) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:57:11.239+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:57:11.241+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:57:11.241+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:57:11.275+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:57:11.272+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:57:11.276+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:57:11.322+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.092 seconds
[2025-02-14T07:57:41.452+0000] {processor.py:154} INFO - Started process (PID=2668) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:57:41.455+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:57:41.458+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:57:41.458+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:57:41.515+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:57:41.511+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:57:41.520+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:57:41.567+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.124 seconds
[2025-02-14T07:58:11.613+0000] {processor.py:154} INFO - Started process (PID=2698) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:58:11.617+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:58:11.619+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:58:11.619+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:58:11.657+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:58:11.652+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:58:11.660+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:58:11.698+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.091 seconds
[2025-02-14T07:58:41.854+0000] {processor.py:154} INFO - Started process (PID=2728) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:58:41.858+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:58:41.861+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:58:41.860+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:58:41.897+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:58:41.894+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:58:41.899+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:58:41.935+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.089 seconds
[2025-02-14T07:59:12.292+0000] {processor.py:154} INFO - Started process (PID=2766) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:59:12.297+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:59:12.305+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:59:12.305+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:59:12.371+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:59:12.365+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:59:12.376+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:59:12.542+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.310 seconds
[2025-02-14T07:59:42.661+0000] {processor.py:154} INFO - Started process (PID=2799) to work on /opt/airflow/dags/consumer.py
[2025-02-14T07:59:42.664+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T07:59:42.667+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:59:42.667+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T07:59:42.705+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:59:42.701+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:59:42.708+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T07:59:42.758+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.107 seconds
[2025-02-14T08:00:13.166+0000] {processor.py:154} INFO - Started process (PID=2830) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:00:13.169+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:00:13.172+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:00:13.172+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:00:13.204+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:00:13.201+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:00:13.206+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:00:13.241+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.082 seconds
[2025-02-14T08:00:43.398+0000] {processor.py:154} INFO - Started process (PID=2869) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:00:43.401+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:00:43.403+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:00:43.403+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:00:43.440+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:00:43.435+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:00:43.443+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:00:43.482+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.090 seconds
[2025-02-14T08:01:13.957+0000] {processor.py:154} INFO - Started process (PID=2900) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:01:13.960+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:01:13.962+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:01:13.962+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:01:13.998+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:01:13.996+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:01:14.001+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:01:14.041+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.090 seconds
[2025-02-14T08:01:44.315+0000] {processor.py:154} INFO - Started process (PID=2940) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:01:44.318+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:01:44.321+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:01:44.321+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:01:44.362+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:01:44.359+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:01:44.364+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:01:44.412+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.105 seconds
[2025-02-14T08:02:14.922+0000] {processor.py:154} INFO - Started process (PID=2971) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:02:14.926+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:02:14.931+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:02:14.931+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:02:14.982+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:02:14.976+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:02:14.984+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:02:15.032+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.120 seconds
[2025-02-14T08:02:45.392+0000] {processor.py:154} INFO - Started process (PID=3011) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:02:45.400+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:02:45.412+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:02:45.410+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:02:45.598+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:02:45.593+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:02:45.603+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:02:45.662+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.283 seconds
[2025-02-14T08:03:15.710+0000] {processor.py:154} INFO - Started process (PID=3041) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:03:15.713+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:03:15.715+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:03:15.715+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:03:15.746+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:03:15.743+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:03:15.748+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:03:15.783+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.078 seconds
[2025-02-14T08:03:45.910+0000] {processor.py:154} INFO - Started process (PID=3079) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:03:45.913+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:03:45.915+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:03:45.915+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:03:45.949+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:03:45.946+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:03:45.952+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:03:45.991+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.086 seconds
[2025-02-14T08:04:16.498+0000] {processor.py:154} INFO - Started process (PID=3111) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:04:16.501+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:04:16.504+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:04:16.504+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:04:16.537+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:04:16.534+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:04:16.540+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:04:16.585+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.093 seconds
[2025-02-14T08:04:46.967+0000] {processor.py:154} INFO - Started process (PID=3142) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:04:46.971+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:04:46.974+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:04:46.973+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:04:47.016+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:04:47.010+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:04:47.018+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:04:47.063+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.102 seconds
[2025-02-14T08:05:17.523+0000] {processor.py:154} INFO - Started process (PID=3183) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:05:17.525+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:05:17.529+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:05:17.529+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:05:17.564+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:05:17.560+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:05:17.567+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:05:17.603+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.086 seconds
[2025-02-14T08:05:48.525+0000] {processor.py:154} INFO - Started process (PID=3215) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:05:48.528+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:05:48.531+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:05:48.531+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:05:48.567+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:05:48.563+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:05:48.570+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:05:48.611+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.092 seconds
[2025-02-14T08:06:19.357+0000] {processor.py:154} INFO - Started process (PID=3253) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:06:19.360+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:06:19.363+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:06:19.363+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:06:19.412+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:06:19.405+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:06:19.414+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:06:19.461+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.112 seconds
[2025-02-14T08:06:49.597+0000] {processor.py:154} INFO - Started process (PID=3286) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:06:49.605+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:06:49.608+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:06:49.607+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:06:49.663+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:06:49.658+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:06:49.666+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:06:49.742+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.161 seconds
[2025-02-14T08:07:20.508+0000] {processor.py:154} INFO - Started process (PID=3318) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:07:20.512+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:07:20.516+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:07:20.516+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:07:20.558+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:07:20.555+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:07:20.560+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:07:20.602+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.099 seconds
[2025-02-14T08:07:51.452+0000] {processor.py:154} INFO - Started process (PID=3357) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:07:51.456+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:07:51.460+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:07:51.460+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:07:51.495+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:07:51.490+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:07:51.497+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:07:51.542+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.096 seconds
[2025-02-14T08:08:21.819+0000] {processor.py:154} INFO - Started process (PID=3388) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:08:21.822+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:08:21.826+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:08:21.826+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:08:21.865+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:08:21.860+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:08:21.867+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:08:21.906+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.092 seconds
[2025-02-14T08:08:52.880+0000] {processor.py:154} INFO - Started process (PID=3429) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:08:52.884+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:08:52.889+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:08:52.888+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:08:52.935+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:08:52.930+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:08:52.937+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:08:52.975+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.103 seconds
[2025-02-14T08:09:23.409+0000] {processor.py:154} INFO - Started process (PID=3460) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:09:23.411+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:09:23.413+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:09:23.413+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:09:23.448+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:09:23.445+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:09:23.452+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:09:23.490+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.087 seconds
[2025-02-14T08:09:53.885+0000] {processor.py:154} INFO - Started process (PID=3501) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:09:53.888+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:09:53.891+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:09:53.890+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:09:53.938+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:09:53.930+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:09:53.942+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:09:53.986+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.109 seconds
[2025-02-14T08:10:24.353+0000] {processor.py:154} INFO - Started process (PID=3532) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:10:24.356+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:10:24.359+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:10:24.359+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:10:24.403+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:10:24.400+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:10:24.406+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:10:24.453+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.111 seconds
[2025-02-14T08:10:54.791+0000] {processor.py:154} INFO - Started process (PID=3571) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:10:54.796+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:10:54.799+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:10:54.799+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:10:54.842+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:10:54.836+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:10:54.846+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:10:54.893+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.110 seconds
[2025-02-14T08:11:25.467+0000] {processor.py:154} INFO - Started process (PID=3601) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:11:25.472+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:11:25.474+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:11:25.474+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:11:25.511+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:11:25.507+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:11:25.514+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:11:25.560+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.098 seconds
[2025-02-14T08:11:56.424+0000] {processor.py:154} INFO - Started process (PID=3642) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:11:56.427+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:11:56.429+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:11:56.429+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:11:56.464+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:11:56.460+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:11:56.466+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:11:56.506+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.087 seconds
[2025-02-14T08:12:26.568+0000] {processor.py:154} INFO - Started process (PID=3671) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:12:26.571+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:12:26.573+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:12:26.573+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:12:26.608+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:12:26.605+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:12:26.611+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:12:26.660+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.100 seconds
[2025-02-14T08:12:57.212+0000] {processor.py:154} INFO - Started process (PID=3709) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:12:57.217+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:12:57.219+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:12:57.219+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:12:57.257+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:12:57.255+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:12:57.259+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:12:57.304+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.102 seconds
[2025-02-14T08:13:27.740+0000] {processor.py:154} INFO - Started process (PID=3742) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:13:27.743+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:13:27.745+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:13:27.745+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:13:27.777+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:13:27.773+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:13:27.778+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:13:27.815+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.081 seconds
[2025-02-14T08:13:58.543+0000] {processor.py:154} INFO - Started process (PID=3772) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:13:58.546+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:13:58.548+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:13:58.548+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:13:58.603+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:13:58.600+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:13:58.606+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:13:58.642+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.106 seconds
[2025-02-14T08:14:29.060+0000] {processor.py:154} INFO - Started process (PID=3811) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:14:29.069+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:14:29.076+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:14:29.075+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:14:29.163+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:14:29.144+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:14:29.166+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:14:29.253+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.207 seconds
[2025-02-14T08:14:59.327+0000] {processor.py:154} INFO - Started process (PID=3841) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:14:59.332+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:14:59.336+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:14:59.336+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:14:59.398+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:14:59.391+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:14:59.405+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:14:59.481+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.163 seconds
[2025-02-14T08:15:29.778+0000] {processor.py:154} INFO - Started process (PID=3880) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:15:29.787+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:15:29.790+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:15:29.790+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:15:29.844+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:15:29.840+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:15:29.848+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:15:29.892+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.124 seconds
[2025-02-14T08:16:00.143+0000] {processor.py:154} INFO - Started process (PID=3911) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:16:00.146+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:16:00.148+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:16:00.148+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:16:00.183+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:16:00.180+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:16:00.184+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:16:00.228+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.093 seconds
[2025-02-14T08:16:30.734+0000] {processor.py:154} INFO - Started process (PID=3948) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:16:30.737+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:16:30.740+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:16:30.739+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:16:30.776+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:16:30.771+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:16:30.778+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:16:30.824+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.097 seconds
[2025-02-14T08:17:01.108+0000] {processor.py:154} INFO - Started process (PID=3981) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:17:01.112+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:17:01.117+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:17:01.117+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:17:01.176+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:17:01.172+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:17:01.179+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:17:01.249+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.148 seconds
[2025-02-14T08:17:31.397+0000] {processor.py:154} INFO - Started process (PID=4012) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:17:31.401+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:17:31.404+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:17:31.404+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:17:31.436+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:17:31.433+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:17:31.438+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:17:31.537+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.145 seconds
[2025-02-14T08:18:01.692+0000] {processor.py:154} INFO - Started process (PID=4052) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:18:01.695+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:18:01.697+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:18:01.697+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:18:01.728+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:18:01.725+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:18:01.731+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:18:01.765+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.079 seconds
[2025-02-14T08:18:32.160+0000] {processor.py:154} INFO - Started process (PID=4083) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:18:32.163+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:18:32.168+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:18:32.165+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:18:32.201+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:18:32.197+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:18:32.205+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:18:32.244+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.089 seconds
[2025-02-14T08:19:02.425+0000] {processor.py:154} INFO - Started process (PID=4123) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:19:02.427+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:19:02.429+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:19:02.429+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:19:02.463+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:19:02.459+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:19:02.466+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:19:02.500+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.081 seconds
[2025-02-14T08:19:32.616+0000] {processor.py:154} INFO - Started process (PID=4154) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:19:32.619+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:19:32.624+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:19:32.624+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:19:32.662+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:19:32.659+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:19:32.664+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:19:32.704+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.095 seconds
[2025-02-14T08:20:02.783+0000] {processor.py:154} INFO - Started process (PID=4192) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:20:02.789+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:20:02.793+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:20:02.793+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:20:02.854+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:20:02.848+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:20:02.857+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:20:02.935+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.159 seconds
[2025-02-14T08:20:33.123+0000] {processor.py:154} INFO - Started process (PID=4222) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:20:33.126+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:20:33.128+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:20:33.128+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:20:33.183+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:20:33.180+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:20:33.185+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:20:33.218+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.102 seconds
[2025-02-14T08:21:03.570+0000] {processor.py:154} INFO - Started process (PID=4253) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:21:03.573+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:21:03.575+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:21:03.575+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:21:03.612+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:21:03.608+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:21:03.613+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:21:03.654+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.089 seconds
[2025-02-14T08:21:34.188+0000] {processor.py:154} INFO - Started process (PID=4293) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:21:34.196+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:21:34.222+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:21:34.222+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:21:34.276+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:21:34.269+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:21:34.278+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:21:34.324+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.149 seconds
[2025-02-14T08:22:04.556+0000] {processor.py:154} INFO - Started process (PID=4324) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:22:04.559+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:22:04.561+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:22:04.561+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:22:04.596+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:22:04.593+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:22:04.599+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:22:04.636+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.087 seconds
[2025-02-14T08:22:34.908+0000] {processor.py:154} INFO - Started process (PID=4355) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:22:34.912+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:22:34.915+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:22:34.914+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:22:34.949+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:22:34.946+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:22:34.952+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:22:34.991+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.090 seconds
[2025-02-14T08:23:05.349+0000] {processor.py:154} INFO - Started process (PID=4393) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:23:05.352+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:23:05.354+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:23:05.354+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:23:05.388+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:23:05.384+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:23:05.390+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:23:05.429+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.089 seconds
[2025-02-14T08:23:35.652+0000] {processor.py:154} INFO - Started process (PID=4423) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:23:35.655+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:23:35.659+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:23:35.659+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:23:35.694+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:23:35.692+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:23:35.696+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:23:35.739+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.093 seconds
[2025-02-14T08:24:05.802+0000] {processor.py:154} INFO - Started process (PID=4463) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:24:05.805+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:24:05.816+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:24:05.816+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:24:05.918+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:24:05.909+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:24:05.923+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:24:05.994+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.201 seconds
[2025-02-14T08:24:36.700+0000] {processor.py:154} INFO - Started process (PID=4494) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:24:36.702+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:24:36.705+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:24:36.705+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:24:36.735+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:24:36.732+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:24:36.737+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:24:36.774+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.080 seconds
[2025-02-14T08:25:06.956+0000] {processor.py:154} INFO - Started process (PID=4534) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:25:06.960+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:25:06.968+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:25:06.967+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:25:07.016+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:25:07.012+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:25:07.020+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:25:07.069+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.119 seconds
[2025-02-14T08:25:37.721+0000] {processor.py:154} INFO - Started process (PID=4563) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:25:37.724+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:25:37.726+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:25:37.726+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:25:37.757+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:25:37.754+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:25:37.759+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:25:37.795+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.079 seconds
[2025-02-14T08:26:07.853+0000] {processor.py:154} INFO - Started process (PID=4594) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:26:07.856+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:26:07.862+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:26:07.862+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:26:07.917+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:26:07.907+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:26:07.920+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:26:07.964+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.120 seconds
[2025-02-14T08:26:38.609+0000] {processor.py:154} INFO - Started process (PID=4634) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:26:38.612+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:26:38.615+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:26:38.615+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:26:38.652+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:26:38.649+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:26:38.655+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:26:38.707+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.103 seconds
[2025-02-14T08:27:08.916+0000] {processor.py:154} INFO - Started process (PID=4665) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:27:08.920+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:27:08.924+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:27:08.924+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:27:08.957+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:27:08.953+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:27:08.959+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:27:08.999+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.089 seconds
[2025-02-14T08:27:39.580+0000] {processor.py:154} INFO - Started process (PID=4703) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:27:39.582+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:27:39.587+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:27:39.586+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:27:39.636+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:27:39.623+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:27:39.639+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:27:39.675+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.102 seconds
[2025-02-14T08:28:10.140+0000] {processor.py:154} INFO - Started process (PID=4733) to work on /opt/airflow/dags/consumer.py
[2025-02-14T08:28:10.143+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/consumer.py for tasks to queue
[2025-02-14T08:28:10.147+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:28:10.147+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/consumer.py
[2025-02-14T08:28:10.180+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:28:10.178+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/consumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:28:10.183+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer.py
[2025-02-14T08:28:10.219+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/consumer.py took 0.086 seconds
