[2025-02-14T07:33:58.694+0000] {processor.py:154} INFO - Started process (PID=1046) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:33:58.697+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:33:58.700+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:33:58.699+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:33:58.749+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:33:58.746+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 28, in <module>
    update_dateset() >> update_dateset_2()
NameError: name 'update_dateset' is not defined
[2025-02-14T07:33:58.751+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:33:58.787+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.099 seconds
[2025-02-14T07:34:29.325+0000] {processor.py:154} INFO - Started process (PID=1077) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:34:29.327+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:34:29.330+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:29.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:34:29.379+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:29.377+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 28, in <module>
    update_dateset() >> update_dateset_2()
NameError: name 'update_dateset' is not defined
[2025-02-14T07:34:29.381+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:34:29.422+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.104 seconds
[2025-02-14T07:34:51.377+0000] {processor.py:154} INFO - Started process (PID=1101) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:34:51.381+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:34:51.384+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:51.384+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:34:51.466+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:34:51.641+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:51.641+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:34:51.700+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:34:51.700+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to 2025-02-13T00:00:00+00:00, run_after=2025-02-14T00:00:00+00:00
[2025-02-14T07:34:51.773+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.404 seconds
[2025-02-14T07:35:22.181+0000] {processor.py:154} INFO - Started process (PID=1141) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:35:22.185+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:35:22.187+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:22.187+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:35:22.239+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:35:22.315+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:22.314+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:35:22.368+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:22.368+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to 2025-02-13T00:00:00+00:00, run_after=2025-02-14T00:00:00+00:00
[2025-02-14T07:35:22.462+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.286 seconds
[2025-02-14T07:35:52.517+0000] {processor.py:154} INFO - Started process (PID=1173) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:35:52.520+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:35:52.522+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:52.522+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:35:52.567+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:35:52.611+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:52.610+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:35:52.663+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:35:52.663+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to 2025-02-13T00:00:00+00:00, run_after=2025-02-14T00:00:00+00:00
[2025-02-14T07:35:52.705+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.193 seconds
[2025-02-14T07:36:23.479+0000] {processor.py:154} INFO - Started process (PID=1203) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:36:23.481+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:36:23.484+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:23.484+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:36:23.529+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:36:23.658+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:23.658+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:36:23.703+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:23.703+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to 2025-02-13T00:00:00+00:00, run_after=2025-02-14T00:00:00+00:00
[2025-02-14T07:36:23.748+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.274 seconds
[2025-02-14T07:36:54.568+0000] {processor.py:154} INFO - Started process (PID=1244) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:36:54.571+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:36:54.574+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:54.574+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:36:54.631+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:36:54.708+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:54.708+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:36:54.763+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:36:54.763+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to 2025-02-13T00:00:00+00:00, run_after=2025-02-14T00:00:00+00:00
[2025-02-14T07:36:54.807+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.246 seconds
[2025-02-14T07:37:25.297+0000] {processor.py:154} INFO - Started process (PID=1275) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:37:25.300+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:37:25.303+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:25.302+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:37:25.356+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:37:25.400+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:25.399+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:37:25.449+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:25.449+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to 2025-02-13T00:00:00+00:00, run_after=2025-02-14T00:00:00+00:00
[2025-02-14T07:37:25.487+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.197 seconds
[2025-02-14T07:37:55.769+0000] {processor.py:154} INFO - Started process (PID=1316) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:37:55.772+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:37:55.777+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:55.776+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:37:55.841+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:37:56.143+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:56.143+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:37:56.356+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:37:56.355+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to 2025-02-13T00:00:00+00:00, run_after=2025-02-14T00:00:00+00:00
[2025-02-14T07:37:56.458+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.698 seconds
[2025-02-14T07:38:27.340+0000] {processor.py:154} INFO - Started process (PID=1348) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:38:27.342+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:38:27.344+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:27.344+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:38:27.395+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:38:27.466+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:27.466+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-14T07:38:27.510+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:27.510+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to 2025-02-13T00:00:00+00:00, run_after=2025-02-14T00:00:00+00:00
[2025-02-14T07:38:27.555+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.221 seconds
[2025-02-14T07:38:54.765+0000] {processor.py:154} INFO - Started process (PID=1379) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:38:54.768+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:38:54.771+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:54.770+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:38:54.824+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:38:54.822+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:38:54.825+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:38:54.855+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.096 seconds
[2025-02-14T07:39:25.077+0000] {processor.py:154} INFO - Started process (PID=1419) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:39:25.079+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:39:25.088+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:39:25.088+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:39:25.121+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:39:25.118+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:39:25.123+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:39:25.158+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.089 seconds
[2025-02-14T07:39:55.810+0000] {processor.py:154} INFO - Started process (PID=1450) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:39:55.814+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:39:55.818+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:39:55.818+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:39:55.851+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:39:55.848+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:39:55.853+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:39:55.885+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.082 seconds
[2025-02-14T07:40:26.226+0000] {processor.py:154} INFO - Started process (PID=1481) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:40:26.230+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:40:26.233+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:40:26.232+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:40:26.269+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:40:26.266+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:40:26.270+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:40:26.302+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.084 seconds
[2025-02-14T07:40:56.644+0000] {processor.py:154} INFO - Started process (PID=1521) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:40:56.647+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:40:56.649+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:40:56.648+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:40:56.690+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:40:56.685+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:40:56.691+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:40:56.725+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.087 seconds
[2025-02-14T07:41:21.581+0000] {processor.py:154} INFO - Started process (PID=1547) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:41:21.586+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:41:21.589+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:41:21.589+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:41:21.652+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:41:21.647+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:41:21.656+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:41:21.705+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.130 seconds
[2025-02-14T07:41:52.003+0000] {processor.py:154} INFO - Started process (PID=1578) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:41:52.007+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:41:52.010+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:41:52.010+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:41:52.109+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:41:52.105+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:41:52.116+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:41:52.170+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.178 seconds
[2025-02-14T07:42:22.618+0000] {processor.py:154} INFO - Started process (PID=1618) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:42:22.621+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:42:22.623+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:42:22.623+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:42:22.660+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:42:22.657+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:42:22.664+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:42:22.701+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.089 seconds
[2025-02-14T07:42:53.226+0000] {processor.py:154} INFO - Started process (PID=1649) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:42:53.229+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:42:53.231+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:42:53.231+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:42:53.263+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:42:53.261+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:42:53.265+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:42:53.298+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.078 seconds
[2025-02-14T07:43:23.983+0000] {processor.py:154} INFO - Started process (PID=1680) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:43:23.993+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:43:24.053+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:43:24.050+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:43:24.105+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:43:24.099+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:43:24.107+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:43:24.152+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.174 seconds
[2025-02-14T07:43:54.904+0000] {processor.py:154} INFO - Started process (PID=1720) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:43:54.907+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:43:54.909+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:43:54.909+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:43:54.946+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:43:54.942+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:43:54.949+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:43:54.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.085 seconds
[2025-02-14T07:44:25.636+0000] {processor.py:154} INFO - Started process (PID=1749) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:44:25.641+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:44:25.643+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:44:25.643+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:44:25.687+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:44:25.684+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:44:25.689+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:44:25.728+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.103 seconds
[2025-02-14T07:44:56.203+0000] {processor.py:154} INFO - Started process (PID=1789) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:44:56.206+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:44:56.209+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:44:56.209+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:44:56.252+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:44:56.248+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:44:56.254+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:44:56.288+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.091 seconds
[2025-02-14T07:45:26.998+0000] {processor.py:154} INFO - Started process (PID=1820) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:45:27.000+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:45:27.003+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:45:27.002+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:45:27.033+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:45:27.029+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:45:27.036+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:45:27.069+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.078 seconds
[2025-02-14T07:45:57.813+0000] {processor.py:154} INFO - Started process (PID=1861) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:45:57.820+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:45:57.823+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:45:57.823+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:45:57.863+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:45:57.859+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:45:57.865+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:45:57.905+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.103 seconds
[2025-02-14T07:46:28.657+0000] {processor.py:154} INFO - Started process (PID=1892) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:46:28.677+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:46:28.747+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:46:28.720+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:46:28.859+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:46:28.851+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:46:28.865+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:46:28.975+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.380 seconds
[2025-02-14T07:46:59.805+0000] {processor.py:154} INFO - Started process (PID=1932) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:46:59.810+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:46:59.814+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:46:59.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:46:59.853+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:46:59.849+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:46:59.855+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:46:59.939+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.139 seconds
[2025-02-14T07:47:30.507+0000] {processor.py:154} INFO - Started process (PID=1962) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:47:30.511+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:47:30.514+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:47:30.513+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:47:30.546+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:47:30.543+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:47:30.548+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:47:30.584+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.083 seconds
[2025-02-14T07:48:01.125+0000] {processor.py:154} INFO - Started process (PID=2002) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:48:01.128+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:48:01.130+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:48:01.130+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:48:01.161+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:48:01.159+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:48:01.163+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:48:01.195+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.075 seconds
[2025-02-14T07:48:31.725+0000] {processor.py:154} INFO - Started process (PID=2033) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:48:31.728+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:48:31.734+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:48:31.734+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:48:31.780+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:48:31.771+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:48:31.782+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:48:31.822+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.103 seconds
[2025-02-14T07:49:01.896+0000] {processor.py:154} INFO - Started process (PID=2073) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:49:01.899+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:49:01.901+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:49:01.901+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:49:01.930+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:49:01.926+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:49:01.933+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:49:01.964+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.074 seconds
[2025-02-14T07:49:32.634+0000] {processor.py:154} INFO - Started process (PID=2103) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:49:32.638+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:49:32.640+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:49:32.640+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:49:32.670+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:49:32.667+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:49:32.672+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:49:32.706+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.077 seconds
[2025-02-14T07:50:02.958+0000] {processor.py:154} INFO - Started process (PID=2143) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:50:02.962+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:50:02.965+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:50:02.965+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:50:03.007+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:50:03.002+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:50:03.011+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:50:03.116+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.167 seconds
[2025-02-14T07:50:33.164+0000] {processor.py:154} INFO - Started process (PID=2174) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:50:33.169+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:50:33.171+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:50:33.171+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:50:33.203+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:50:33.200+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:50:33.205+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:50:33.238+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.079 seconds
[2025-02-14T07:51:03.536+0000] {processor.py:154} INFO - Started process (PID=2204) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:51:03.539+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:51:03.541+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:51:03.541+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:51:03.571+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:51:03.569+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:51:03.573+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:51:03.606+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.075 seconds
[2025-02-14T07:51:33.923+0000] {processor.py:154} INFO - Started process (PID=2244) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:51:33.926+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:51:33.930+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:51:33.929+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:51:33.965+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:51:33.961+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:51:33.967+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:51:34.002+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.085 seconds
[2025-02-14T07:52:04.668+0000] {processor.py:154} INFO - Started process (PID=2275) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:52:04.672+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:52:04.687+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:52:04.687+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:52:04.724+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:52:04.721+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:52:04.726+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:52:04.762+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.159 seconds
[2025-02-14T07:52:35.228+0000] {processor.py:154} INFO - Started process (PID=2315) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:52:35.231+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:52:35.234+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:52:35.233+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:52:35.266+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:52:35.263+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:52:35.268+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:52:35.303+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.080 seconds
[2025-02-14T07:53:05.846+0000] {processor.py:154} INFO - Started process (PID=2346) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:53:05.850+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:53:05.852+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:53:05.852+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:53:05.881+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:53:05.879+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:53:05.883+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:53:05.919+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.078 seconds
[2025-02-14T07:53:36.173+0000] {processor.py:154} INFO - Started process (PID=2386) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:53:36.176+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:53:36.179+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:53:36.179+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:53:36.224+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:53:36.221+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:53:36.227+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:53:36.265+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.098 seconds
[2025-02-14T07:54:06.641+0000] {processor.py:154} INFO - Started process (PID=2417) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:54:06.644+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:54:06.646+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:54:06.646+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:54:06.680+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:54:06.676+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:54:06.682+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:54:06.718+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.083 seconds
[2025-02-14T07:54:37.451+0000] {processor.py:154} INFO - Started process (PID=2456) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:54:37.454+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:54:37.456+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:54:37.456+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:54:37.492+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:54:37.488+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:54:37.495+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:54:37.546+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.102 seconds
[2025-02-14T07:55:07.807+0000] {processor.py:154} INFO - Started process (PID=2487) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:55:07.812+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:55:07.814+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:55:07.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:55:07.850+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:55:07.846+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:55:07.853+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:55:07.895+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.113 seconds
[2025-02-14T07:55:38.176+0000] {processor.py:154} INFO - Started process (PID=2526) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:55:38.179+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:55:38.182+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:55:38.181+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:55:38.215+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:55:38.212+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:55:38.217+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:55:38.253+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.084 seconds
[2025-02-14T07:56:08.518+0000] {processor.py:154} INFO - Started process (PID=2557) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:56:08.522+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:56:08.524+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:56:08.524+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:56:08.554+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:56:08.551+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:56:08.555+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:56:08.588+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.075 seconds
[2025-02-14T07:56:39.405+0000] {processor.py:154} INFO - Started process (PID=2597) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:56:39.408+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:56:39.412+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:56:39.412+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:56:39.453+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:56:39.450+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:56:39.457+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:56:39.491+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.095 seconds
[2025-02-14T07:57:10.114+0000] {processor.py:154} INFO - Started process (PID=2628) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:57:10.118+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:57:10.121+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:57:10.121+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:57:10.156+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:57:10.153+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:57:10.158+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:57:10.199+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.092 seconds
[2025-02-14T07:57:40.299+0000] {processor.py:154} INFO - Started process (PID=2658) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:57:40.303+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:57:40.306+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:57:40.306+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:57:40.348+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:57:40.344+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:57:40.350+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:57:40.395+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.105 seconds
[2025-02-14T07:58:10.495+0000] {processor.py:154} INFO - Started process (PID=2696) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:58:10.498+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:58:10.499+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:58:10.499+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:58:10.529+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:58:10.526+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:58:10.531+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:58:10.563+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.074 seconds
[2025-02-14T07:58:40.843+0000] {processor.py:154} INFO - Started process (PID=2727) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:58:40.849+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:58:40.853+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:58:40.853+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:58:40.882+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:58:40.880+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:58:40.885+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:58:40.918+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.081 seconds
[2025-02-14T07:59:11.452+0000] {processor.py:154} INFO - Started process (PID=2765) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:59:11.520+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:59:11.604+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:59:11.603+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:59:12.192+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:59:12.185+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:59:12.204+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:59:12.355+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.924 seconds
[2025-02-14T07:59:42.649+0000] {processor.py:154} INFO - Started process (PID=2798) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T07:59:42.652+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T07:59:42.654+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:59:42.654+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T07:59:42.694+0000] {logging_mixin.py:120} INFO - [2025-02-14T07:59:42.690+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T07:59:42.696+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T07:59:42.741+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.102 seconds
[2025-02-14T08:00:13.160+0000] {processor.py:154} INFO - Started process (PID=2829) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:00:13.164+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:00:13.166+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:00:13.166+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:00:13.202+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:00:13.199+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:00:13.205+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:00:13.243+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.091 seconds
[2025-02-14T08:00:43.390+0000] {processor.py:154} INFO - Started process (PID=2868) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:00:43.393+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:00:43.395+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:00:43.395+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:00:43.430+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:00:43.427+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:00:43.431+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:00:43.474+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.090 seconds
[2025-02-14T08:01:13.951+0000] {processor.py:154} INFO - Started process (PID=2899) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:01:13.955+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:01:13.957+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:01:13.957+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:01:13.992+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:01:13.989+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:01:13.994+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:01:14.033+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.088 seconds
[2025-02-14T08:01:44.310+0000] {processor.py:154} INFO - Started process (PID=2939) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:01:44.316+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:01:44.318+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:01:44.318+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:01:44.355+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:01:44.352+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:01:44.357+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:01:44.406+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.105 seconds
[2025-02-14T08:02:14.907+0000] {processor.py:154} INFO - Started process (PID=2970) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:02:14.910+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:02:14.913+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:02:14.913+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:02:14.959+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:02:14.955+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:02:14.963+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:02:15.011+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.112 seconds
[2025-02-14T08:02:45.225+0000] {processor.py:154} INFO - Started process (PID=3010) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:02:45.230+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:02:45.232+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:02:45.232+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:02:45.274+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:02:45.271+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:02:45.277+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:02:45.327+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.108 seconds
[2025-02-14T08:03:15.594+0000] {processor.py:154} INFO - Started process (PID=3040) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:03:15.598+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:03:15.601+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:03:15.601+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:03:15.639+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:03:15.636+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:03:15.641+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:03:15.674+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.088 seconds
[2025-02-14T08:03:45.787+0000] {processor.py:154} INFO - Started process (PID=3078) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:03:45.791+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:03:45.794+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:03:45.794+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:03:45.831+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:03:45.826+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:03:45.834+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:03:45.872+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.093 seconds
[2025-02-14T08:04:16.493+0000] {processor.py:154} INFO - Started process (PID=3110) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:04:16.496+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:04:16.498+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:04:16.498+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:04:16.533+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:04:16.530+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:04:16.535+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:04:16.576+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.089 seconds
[2025-02-14T08:04:46.957+0000] {processor.py:154} INFO - Started process (PID=3141) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:04:46.961+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:04:46.964+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:04:46.963+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:04:47.011+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:04:47.007+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:04:47.016+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:04:47.058+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.109 seconds
[2025-02-14T08:05:17.519+0000] {processor.py:154} INFO - Started process (PID=3182) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:05:17.522+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:05:17.525+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:05:17.525+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:05:17.562+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:05:17.558+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:05:17.564+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:05:17.606+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.096 seconds
[2025-02-14T08:05:48.521+0000] {processor.py:154} INFO - Started process (PID=3214) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:05:48.525+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:05:48.528+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:05:48.528+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:05:48.565+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:05:48.562+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:05:48.567+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:05:48.611+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.099 seconds
[2025-02-14T08:06:19.350+0000] {processor.py:154} INFO - Started process (PID=3252) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:06:19.353+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:06:19.356+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:06:19.356+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:06:19.396+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:06:19.392+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:06:19.400+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:06:19.448+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.107 seconds
[2025-02-14T08:06:49.577+0000] {processor.py:154} INFO - Started process (PID=3285) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:06:49.582+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:06:49.588+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:06:49.587+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:06:49.645+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:06:49.642+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:06:49.648+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:06:49.713+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.143 seconds
[2025-02-14T08:07:20.504+0000] {processor.py:154} INFO - Started process (PID=3317) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:07:20.507+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:07:20.509+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:07:20.509+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:07:20.553+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:07:20.549+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:07:20.555+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:07:20.596+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.098 seconds
[2025-02-14T08:07:51.448+0000] {processor.py:154} INFO - Started process (PID=3356) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:07:51.452+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:07:51.454+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:07:51.454+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:07:51.495+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:07:51.490+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:07:51.499+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:07:51.536+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.096 seconds
[2025-02-14T08:08:21.814+0000] {processor.py:154} INFO - Started process (PID=3387) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:08:21.817+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:08:21.819+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:08:21.818+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:08:21.855+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:08:21.851+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:08:21.859+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:08:21.899+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.092 seconds
[2025-02-14T08:08:52.874+0000] {processor.py:154} INFO - Started process (PID=3428) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:08:52.878+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:08:52.880+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:08:52.880+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:08:52.927+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:08:52.924+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:08:52.930+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:08:52.973+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.109 seconds
[2025-02-14T08:09:23.403+0000] {processor.py:154} INFO - Started process (PID=3459) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:09:23.407+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:09:23.409+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:09:23.409+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:09:23.443+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:09:23.440+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:09:23.446+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:09:23.489+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.092 seconds
[2025-02-14T08:09:53.876+0000] {processor.py:154} INFO - Started process (PID=3500) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:09:53.880+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:09:53.883+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:09:53.883+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:09:53.928+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:09:53.924+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:09:53.930+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:09:53.977+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.109 seconds
[2025-02-14T08:10:24.341+0000] {processor.py:154} INFO - Started process (PID=3531) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:10:24.347+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:10:24.349+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:10:24.349+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:10:24.394+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:10:24.390+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:10:24.397+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:10:24.446+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.113 seconds
[2025-02-14T08:10:54.780+0000] {processor.py:154} INFO - Started process (PID=3570) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:10:54.784+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:10:54.790+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:10:54.787+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:10:54.832+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:10:54.829+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:10:54.835+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:10:54.880+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.111 seconds
[2025-02-14T08:11:25.462+0000] {processor.py:154} INFO - Started process (PID=3600) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:11:25.465+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:11:25.467+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:11:25.467+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:11:25.505+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:11:25.500+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:11:25.507+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:11:25.562+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.107 seconds
[2025-02-14T08:11:56.305+0000] {processor.py:154} INFO - Started process (PID=3641) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:11:56.308+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:11:56.310+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:11:56.310+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:11:56.347+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:11:56.344+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:11:56.349+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:11:56.385+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.088 seconds
[2025-02-14T08:12:26.557+0000] {processor.py:154} INFO - Started process (PID=3670) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:12:26.560+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:12:26.562+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:12:26.562+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:12:26.596+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:12:26.594+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:12:26.600+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:12:26.644+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.093 seconds
[2025-02-14T08:12:57.202+0000] {processor.py:154} INFO - Started process (PID=3708) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:12:57.206+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:12:57.208+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:12:57.208+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:12:57.253+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:12:57.250+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:12:57.256+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:12:57.300+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.106 seconds
[2025-02-14T08:13:27.736+0000] {processor.py:154} INFO - Started process (PID=3741) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:13:27.740+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:13:27.743+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:13:27.743+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:13:27.777+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:13:27.773+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:13:27.779+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:13:27.815+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.085 seconds
[2025-02-14T08:13:58.538+0000] {processor.py:154} INFO - Started process (PID=3771) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:13:58.540+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:13:58.543+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:13:58.542+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:13:58.591+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:13:58.587+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:13:58.592+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:13:58.634+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.104 seconds
[2025-02-14T08:14:29.050+0000] {processor.py:154} INFO - Started process (PID=3810) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:14:29.060+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:14:29.065+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:14:29.064+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:14:29.146+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:14:29.137+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:14:29.152+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:14:29.231+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.196 seconds
[2025-02-14T08:14:59.317+0000] {processor.py:154} INFO - Started process (PID=3840) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:14:59.323+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:14:59.328+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:14:59.328+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:14:59.392+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:14:59.387+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:14:59.395+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:14:59.472+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.164 seconds
[2025-02-14T08:15:29.767+0000] {processor.py:154} INFO - Started process (PID=3879) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:15:29.770+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:15:29.774+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:15:29.773+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:15:29.822+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:15:29.819+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:15:29.825+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:15:29.871+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.113 seconds
[2025-02-14T08:16:00.132+0000] {processor.py:154} INFO - Started process (PID=3910) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:16:00.134+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:16:00.136+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:16:00.136+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:16:00.172+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:16:00.168+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:16:00.175+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:16:00.216+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.091 seconds
[2025-02-14T08:16:30.724+0000] {processor.py:154} INFO - Started process (PID=3947) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:16:30.728+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:16:30.732+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:16:30.732+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:16:30.769+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:16:30.766+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:16:30.771+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:16:30.810+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.092 seconds
[2025-02-14T08:17:01.097+0000] {processor.py:154} INFO - Started process (PID=3980) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:17:01.100+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:17:01.104+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:17:01.103+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:17:01.158+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:17:01.154+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:17:01.161+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:17:01.215+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.125 seconds
[2025-02-14T08:17:31.270+0000] {processor.py:154} INFO - Started process (PID=4010) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:17:31.273+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:17:31.275+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:17:31.275+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:17:31.308+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:17:31.305+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:17:31.312+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:17:31.360+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.097 seconds
[2025-02-14T08:18:01.687+0000] {processor.py:154} INFO - Started process (PID=4051) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:18:01.690+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:18:01.693+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:18:01.692+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:18:01.726+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:18:01.724+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:18:01.728+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:18:01.768+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.087 seconds
[2025-02-14T08:18:32.153+0000] {processor.py:154} INFO - Started process (PID=4082) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:18:32.156+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:18:32.158+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:18:32.158+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:18:32.192+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:18:32.189+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:18:32.193+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:18:32.232+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.085 seconds
[2025-02-14T08:19:02.421+0000] {processor.py:154} INFO - Started process (PID=4122) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:19:02.424+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:19:02.426+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:19:02.426+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:19:02.459+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:19:02.457+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:19:02.462+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:19:02.499+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.084 seconds
[2025-02-14T08:19:32.610+0000] {processor.py:154} INFO - Started process (PID=4153) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:19:32.613+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:19:32.616+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:19:32.616+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:19:32.658+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:19:32.655+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:19:32.661+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:19:32.705+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.104 seconds
[2025-02-14T08:20:02.788+0000] {processor.py:154} INFO - Started process (PID=4191) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:20:02.793+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:20:02.796+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:20:02.796+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:20:02.858+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:20:02.852+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:20:02.863+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:20:02.936+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.161 seconds
[2025-02-14T08:20:33.118+0000] {processor.py:154} INFO - Started process (PID=4221) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:20:33.121+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:20:33.124+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:20:33.123+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:20:33.157+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:20:33.154+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:20:33.160+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:20:33.200+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.087 seconds
[2025-02-14T08:21:03.564+0000] {processor.py:154} INFO - Started process (PID=4252) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:21:03.566+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:21:03.568+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:21:03.568+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:21:03.606+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:21:03.602+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:21:03.608+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:21:03.651+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.094 seconds
[2025-02-14T08:21:34.174+0000] {processor.py:154} INFO - Started process (PID=4292) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:21:34.179+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:21:34.183+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:21:34.182+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:21:34.244+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:21:34.239+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:21:34.246+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:21:34.307+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.141 seconds
[2025-02-14T08:22:04.549+0000] {processor.py:154} INFO - Started process (PID=4323) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:22:04.551+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:22:04.553+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:22:04.552+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:22:04.585+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:22:04.582+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:22:04.587+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:22:04.626+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.082 seconds
[2025-02-14T08:22:34.748+0000] {processor.py:154} INFO - Started process (PID=4354) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:22:34.753+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:22:34.757+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:22:34.757+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:22:34.811+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:22:34.807+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:22:34.814+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:22:34.866+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.126 seconds
[2025-02-14T08:23:05.251+0000] {processor.py:154} INFO - Started process (PID=4392) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:23:05.254+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:23:05.256+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:23:05.255+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:23:05.296+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:23:05.291+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:23:05.298+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:23:05.338+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.092 seconds
[2025-02-14T08:23:35.647+0000] {processor.py:154} INFO - Started process (PID=4422) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:23:35.651+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:23:35.653+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:23:35.653+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:23:35.685+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:23:35.682+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:23:35.686+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:23:35.726+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.086 seconds
[2025-02-14T08:24:05.794+0000] {processor.py:154} INFO - Started process (PID=4462) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:24:05.800+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:24:05.809+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:24:05.809+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:24:05.908+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:24:05.903+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:24:05.911+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:24:05.990+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.205 seconds
[2025-02-14T08:24:36.694+0000] {processor.py:154} INFO - Started process (PID=4493) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:24:36.697+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:24:36.700+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:24:36.700+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:24:36.736+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:24:36.733+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:24:36.738+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:24:36.776+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.088 seconds
[2025-02-14T08:25:06.950+0000] {processor.py:154} INFO - Started process (PID=4533) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:25:06.954+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:25:06.956+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:25:06.956+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:25:07.002+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:25:06.998+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:25:07.007+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:25:07.059+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.115 seconds
[2025-02-14T08:25:37.716+0000] {processor.py:154} INFO - Started process (PID=4562) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:25:37.719+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:25:37.721+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:25:37.721+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:25:37.753+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:25:37.750+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:25:37.756+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:25:37.794+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.084 seconds
[2025-02-14T08:26:07.845+0000] {processor.py:154} INFO - Started process (PID=4593) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:26:07.849+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:26:07.852+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:26:07.852+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:26:07.919+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:26:07.914+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:26:07.921+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:26:07.965+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.131 seconds
[2025-02-14T08:26:38.606+0000] {processor.py:154} INFO - Started process (PID=4633) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:26:38.609+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:26:38.612+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:26:38.612+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:26:38.651+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:26:38.646+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:26:38.654+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:26:38.702+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.103 seconds
[2025-02-14T08:27:08.909+0000] {processor.py:154} INFO - Started process (PID=4664) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:27:08.912+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:27:08.916+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:27:08.916+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:27:08.951+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:27:08.948+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:27:08.953+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:27:08.990+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.087 seconds
[2025-02-14T08:27:39.574+0000] {processor.py:154} INFO - Started process (PID=4702) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:27:39.577+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:27:39.580+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:27:39.579+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:27:39.622+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:27:39.618+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:27:39.628+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:27:39.674+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.106 seconds
[2025-02-14T08:28:10.132+0000] {processor.py:154} INFO - Started process (PID=4732) to work on /opt/airflow/dags/producer_2.py
[2025-02-14T08:28:10.136+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer_2.py for tasks to queue
[2025-02-14T08:28:10.139+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:28:10.139+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer_2.py
[2025-02-14T08:28:10.175+0000] {logging_mixin.py:120} INFO - [2025-02-14T08:28:10.172+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer_2.py", line 3, in <module>
    from include.datasets import my_file
ModuleNotFoundError: No module named 'include'
[2025-02-14T08:28:10.177+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer_2.py
[2025-02-14T08:28:10.212+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer_2.py took 0.088 seconds
