[2025-02-04T04:26:52.447+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table __airflow_temporary_run_2025-02-04T04:26:51.687012+00:00__ [None]>
[2025-02-04T04:26:52.463+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table __airflow_temporary_run_2025-02-04T04:26:51.687012+00:00__ [None]>
[2025-02-04T04:26:52.463+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-02-04T04:26:52.464+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-02-04T04:26:52.464+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-02-04T04:26:52.493+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-01-01 00:00:00+00:00
[2025-02-04T04:26:52.499+0000] {standard_task_runner.py:55} INFO - Started process 1135 to run task
[2025-02-04T04:26:52.505+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', '__***_temporary_run_2025-02-04T04:26:51.687012+00:00__', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpm_ztpk8e']
[2025-02-04T04:26:52.506+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask create_table
[2025-02-04T04:26:52.604+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table __airflow_temporary_run_2025-02-04T04:26:51.687012+00:00__ [running]> on host fb1f760c5ca3
[2025-02-04T04:26:52.713+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2025-02-04T04:26:51.687012+00:00__
[2025-02-04T04:26:52.728+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-02-04T04:26:52.733+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
                );
            , parameters: None
[2025-02-04T04:26:52.735+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2025-02-04T04:26:52.749+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230101T000000, start_date=20250204T042652, end_date=20250204T042652
[2025-02-04T04:26:52.771+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-02-04T04:26:52.800+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
