[2025-02-11T06:39:51.046+0000] {processor.py:154} INFO - Started process (PID=3195) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:39:51.047+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:39:51.049+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:39:51.048+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:39:51.088+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:39:51.423+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:39:51.423+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:group_dag
[2025-02-11T06:39:51.440+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:39:51.439+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:group_dag
[2025-02-11T06:39:51.452+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:39:51.451+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:group_dag
[2025-02-11T06:39:51.452+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:39:51.452+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:39:51.630+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:39:51.630+0000] {dag.py:2606} INFO - Creating ORM DAG for group_dag
[2025-02-11T06:39:51.668+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:39:51.668+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:39:51.716+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.681 seconds
[2025-02-11T06:40:22.383+0000] {processor.py:154} INFO - Started process (PID=3227) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:40:22.385+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:40:22.395+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:40:22.395+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:40:22.469+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:40:22.579+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:40:22.578+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:40:22.670+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:40:22.669+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:40:22.730+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.356 seconds
[2025-02-11T06:40:53.197+0000] {processor.py:154} INFO - Started process (PID=3251) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:40:53.198+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:40:53.200+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:40:53.199+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:40:53.238+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:40:53.321+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:40:53.320+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:40:53.426+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:40:53.426+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:40:53.489+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.297 seconds
[2025-02-11T06:41:24.207+0000] {processor.py:154} INFO - Started process (PID=3274) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:41:24.209+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:41:24.211+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:41:24.210+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:41:24.254+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:41:24.342+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:41:24.342+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:41:24.402+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:41:24.402+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:41:24.526+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.325 seconds
[2025-02-11T06:41:55.303+0000] {processor.py:154} INFO - Started process (PID=3305) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:41:55.314+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:41:55.319+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:41:55.318+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:41:55.370+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:41:55.464+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:41:55.463+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:41:55.534+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:41:55.534+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:41:55.576+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.363 seconds
[2025-02-11T06:42:26.203+0000] {processor.py:154} INFO - Started process (PID=3329) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:42:26.204+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:42:26.209+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:42:26.209+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:42:26.251+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:42:26.347+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:42:26.347+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:42:26.400+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:42:26.399+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:42:26.441+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.244 seconds
[2025-02-11T06:42:57.134+0000] {processor.py:154} INFO - Started process (PID=3362) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:42:57.136+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:42:57.138+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:42:57.138+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:42:57.179+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:42:57.279+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:42:57.278+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:42:57.346+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:42:57.346+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:42:57.390+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.263 seconds
[2025-02-11T06:43:27.950+0000] {processor.py:154} INFO - Started process (PID=3385) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:43:27.952+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:43:27.954+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:43:27.954+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:43:28.014+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:43:28.093+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:43:28.093+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:43:28.154+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:43:28.154+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:43:28.194+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.250 seconds
[2025-02-11T06:43:58.632+0000] {processor.py:154} INFO - Started process (PID=3409) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:43:58.634+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:43:58.636+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:43:58.635+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:43:58.673+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:43:58.759+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:43:58.759+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:43:58.834+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:43:58.833+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:43:58.875+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.249 seconds
[2025-02-11T06:44:29.065+0000] {processor.py:154} INFO - Started process (PID=3442) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:44:29.066+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:44:29.068+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:44:29.067+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:44:29.106+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:44:29.267+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:44:29.266+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:44:29.357+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:44:29.357+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:44:29.404+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.348 seconds
[2025-02-11T06:44:59.605+0000] {processor.py:154} INFO - Started process (PID=3467) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:44:59.607+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:44:59.610+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:44:59.609+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:44:59.651+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:44:59.732+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:44:59.732+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:44:59.788+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:44:59.787+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:44:59.831+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.232 seconds
[2025-02-11T06:45:26.446+0000] {processor.py:154} INFO - Started process (PID=3491) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:45:26.447+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:45:26.448+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:45:26.448+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:45:26.494+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:45:26.755+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:45:26.751+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:45:27.327+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:45:27.327+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:45:27.459+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.021 seconds
[2025-02-11T06:45:57.974+0000] {processor.py:154} INFO - Started process (PID=3516) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:45:57.976+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:45:57.980+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:45:57.979+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:45:58.020+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:45:58.105+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:45:58.104+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:45:58.166+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:45:58.166+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:45:58.210+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.242 seconds
[2025-02-11T06:46:28.301+0000] {processor.py:154} INFO - Started process (PID=3547) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:46:28.303+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:46:28.305+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:46:28.304+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:46:28.354+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:46:28.450+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:46:28.450+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:46:28.516+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:46:28.516+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:46:28.560+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.267 seconds
[2025-02-11T06:46:58.651+0000] {processor.py:154} INFO - Started process (PID=3574) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:46:58.653+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:46:58.654+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:46:58.654+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:46:58.694+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:46:58.781+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:46:58.781+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:46:58.859+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:46:58.858+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:46:58.901+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.255 seconds
[2025-02-11T06:47:16.952+0000] {processor.py:154} INFO - Started process (PID=3585) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:47:16.957+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:47:16.962+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:47:16.961+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:47:17.456+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:47:17.772+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:47:17.771+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:47:17.878+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:47:17.878+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:47:18.294+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.352 seconds
[2025-02-11T06:47:48.715+0000] {processor.py:154} INFO - Started process (PID=3617) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:47:48.717+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:47:48.718+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:47:48.718+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:47:48.763+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:47:48.849+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:47:48.848+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:47:48.913+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:47:48.912+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:47:48.960+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.250 seconds
[2025-02-11T06:48:19.097+0000] {processor.py:154} INFO - Started process (PID=3644) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:48:19.099+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:48:19.101+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:48:19.101+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:48:19.147+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:48:19.387+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:48:19.387+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:48:19.589+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:48:19.588+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:48:19.662+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.573 seconds
[2025-02-11T06:48:49.855+0000] {processor.py:154} INFO - Started process (PID=3668) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:48:49.858+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:48:49.862+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:48:49.862+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:48:49.924+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:48:50.038+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:48:50.038+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:48:50.109+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:48:50.109+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:48:50.169+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.323 seconds
[2025-02-11T06:49:20.347+0000] {processor.py:154} INFO - Started process (PID=3693) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:49:20.349+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:49:20.350+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:49:20.350+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:49:20.396+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:49:20.507+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:49:20.506+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:49:20.619+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:49:20.619+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:49:20.677+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.338 seconds
[2025-02-11T06:49:51.445+0000] {processor.py:154} INFO - Started process (PID=3725) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:49:51.448+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:49:51.449+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:49:51.449+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:49:51.497+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:49:51.589+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:49:51.589+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T06:49:51.670+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:49:51.669+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T06:49:51.716+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.278 seconds
[2025-02-11T06:50:10.229+0000] {processor.py:154} INFO - Started process (PID=3743) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:50:10.231+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:50:10.233+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:50:10.233+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:50:10.258+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:50:10.251+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:50:10.259+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:50:10.320+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.099 seconds
[2025-02-11T06:50:40.362+0000] {processor.py:154} INFO - Started process (PID=3768) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:50:40.363+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:50:40.364+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:50:40.364+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:50:40.372+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:50:40.370+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:50:40.373+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:50:40.428+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.074 seconds
[2025-02-11T06:51:10.972+0000] {processor.py:154} INFO - Started process (PID=3803) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:51:10.974+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:51:10.975+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:51:10.975+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:51:10.990+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:51:10.988+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:51:10.994+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:51:11.059+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.094 seconds
[2025-02-11T06:51:41.617+0000] {processor.py:154} INFO - Started process (PID=3827) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:51:41.620+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:51:41.623+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:51:41.623+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:51:41.633+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:51:41.630+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:51:41.634+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:51:41.680+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.076 seconds
[2025-02-11T06:52:11.947+0000] {processor.py:154} INFO - Started process (PID=3850) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:52:11.949+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:52:11.950+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:52:11.950+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:52:11.958+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:52:11.956+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:52:11.959+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:52:11.997+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.059 seconds
[2025-02-11T06:52:42.802+0000] {processor.py:154} INFO - Started process (PID=3885) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:52:42.804+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:52:42.806+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:52:42.806+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:52:42.820+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:52:42.817+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:52:42.821+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:52:42.896+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.167 seconds
[2025-02-11T06:53:13.579+0000] {processor.py:154} INFO - Started process (PID=3910) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:53:13.581+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:53:13.583+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:53:13.582+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:53:13.593+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:53:13.591+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:53:13.594+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:53:13.642+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.068 seconds
[2025-02-11T06:53:43.921+0000] {processor.py:154} INFO - Started process (PID=3944) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:53:43.923+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:53:43.925+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:53:43.924+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:53:43.936+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:53:43.933+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:53:43.937+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:53:43.991+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.079 seconds
[2025-02-11T06:54:14.674+0000] {processor.py:154} INFO - Started process (PID=3968) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:54:14.675+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:54:14.677+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:54:14.676+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:54:14.684+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:54:14.682+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:54:14.684+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:54:14.723+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.057 seconds
[2025-02-11T06:54:45.037+0000] {processor.py:154} INFO - Started process (PID=3993) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:54:45.040+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:54:45.041+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:54:45.041+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:54:45.051+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:54:45.049+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:54:45.052+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:54:45.305+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.280 seconds
[2025-02-11T06:55:15.478+0000] {processor.py:154} INFO - Started process (PID=4027) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:15.481+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:55:15.483+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:55:15.483+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:15.497+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:55:15.495+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:55:15.499+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:15.547+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.076 seconds
[2025-02-11T06:55:45.710+0000] {processor.py:154} INFO - Started process (PID=4052) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:45.712+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:55:45.714+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:55:45.713+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:45.727+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:55:45.724+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 29
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:55:45.728+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:45.805+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.103 seconds
[2025-02-11T06:55:46.808+0000] {processor.py:154} INFO - Started process (PID=4053) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:46.811+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:55:46.813+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:55:46.812+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:46.906+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:55:46.903+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 32
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:55:46.908+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:55:47.027+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.228 seconds
[2025-02-11T06:56:17.312+0000] {processor.py:154} INFO - Started process (PID=4078) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:17.314+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:56:17.316+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:56:17.316+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:17.331+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:56:17.328+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 32
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:56:17.333+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:17.389+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.084 seconds
[2025-02-11T06:56:22.365+0000] {processor.py:154} INFO - Started process (PID=4079) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:22.367+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:56:22.372+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:56:22.371+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:22.380+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:56:22.379+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 32
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:56:22.381+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:22.462+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.105 seconds
[2025-02-11T06:56:48.158+0000] {processor.py:154} INFO - Started process (PID=4102) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:48.161+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:56:48.163+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:56:48.162+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:48.173+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:56:48.171+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 32
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:56:48.175+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:56:48.226+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.087 seconds
[2025-02-11T06:57:18.581+0000] {processor.py:154} INFO - Started process (PID=4125) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:57:18.583+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:57:18.585+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:57:18.584+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:57:18.592+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:57:18.591+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 32
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:57:18.593+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:57:18.636+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.063 seconds
[2025-02-11T06:57:49.388+0000] {processor.py:154} INFO - Started process (PID=4159) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:57:49.389+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:57:49.392+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:57:49.391+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:57:49.401+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:57:49.399+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 32
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:57:49.402+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:57:49.449+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.069 seconds
[2025-02-11T06:58:20.167+0000] {processor.py:154} INFO - Started process (PID=4184) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:20.169+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:58:20.174+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:58:20.174+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:20.183+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:58:20.181+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 32
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:58:20.184+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:20.223+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.061 seconds
[2025-02-11T06:58:50.992+0000] {processor.py:154} INFO - Started process (PID=4216) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:50.994+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:58:50.996+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:58:50.996+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:51.013+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:58:51.011+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 32
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:58:51.013+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:51.057+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.072 seconds
[2025-02-11T06:58:56.144+0000] {processor.py:154} INFO - Started process (PID=4219) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:56.146+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:58:56.148+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:58:56.148+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:56.159+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:58:56.157+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:58:56.161+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:58:56.229+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.100 seconds
[2025-02-11T06:59:21.324+0000] {processor.py:154} INFO - Started process (PID=4244) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:59:21.326+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:59:21.328+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:59:21.327+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:59:21.339+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:59:21.338+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:59:21.340+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:59:21.384+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.066 seconds
[2025-02-11T06:59:51.741+0000] {processor.py:154} INFO - Started process (PID=4269) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T06:59:51.743+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T06:59:51.745+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:59:51.745+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T06:59:51.755+0000] {logging_mixin.py:120} INFO - [2025-02-11T06:59:51.753+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T06:59:51.755+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T06:59:51.804+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.069 seconds
[2025-02-11T07:00:21.846+0000] {processor.py:154} INFO - Started process (PID=4299) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:00:21.848+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:00:21.851+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:00:21.851+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:00:21.866+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:00:21.864+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:00:21.868+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:00:21.928+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.092 seconds
[2025-02-11T07:02:20.617+0000] {processor.py:154} INFO - Started process (PID=54) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:02:20.629+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:02:20.634+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:02:20.634+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:02:20.654+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:02:20.652+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:02:20.656+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:02:20.782+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.235 seconds
[2025-02-11T07:02:51.805+0000] {processor.py:154} INFO - Started process (PID=78) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:02:51.818+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:02:51.822+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:02:51.822+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:02:51.836+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:02:51.834+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:02:51.845+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:02:51.918+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.120 seconds
[2025-02-11T07:03:22.630+0000] {processor.py:154} INFO - Started process (PID=103) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:03:22.636+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:03:22.639+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:03:22.638+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:03:22.652+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:03:22.649+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:03:22.654+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:03:22.726+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.108 seconds
[2025-02-11T07:03:53.632+0000] {processor.py:154} INFO - Started process (PID=127) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:03:53.635+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:03:53.638+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:03:53.637+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:03:53.649+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:03:53.647+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:03:53.651+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:03:53.728+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.109 seconds
[2025-02-11T07:04:24.448+0000] {processor.py:154} INFO - Started process (PID=159) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:04:24.456+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:04:24.459+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:04:24.459+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:04:24.727+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:04:24.506+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:04:24.839+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:04:25.089+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.662 seconds
[2025-02-11T07:04:55.224+0000] {processor.py:154} INFO - Started process (PID=186) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:04:55.226+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:04:55.228+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:04:55.228+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:04:55.246+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:04:55.244+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:04:55.250+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:04:55.342+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.126 seconds
[2025-02-11T07:05:25.470+0000] {processor.py:154} INFO - Started process (PID=211) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:05:25.473+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:05:25.475+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:05:25.474+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:05:25.484+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:05:25.482+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:05:25.486+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:05:25.554+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.097 seconds
[2025-02-11T07:05:56.383+0000] {processor.py:154} INFO - Started process (PID=236) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:05:56.385+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:05:56.387+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:05:56.386+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:05:56.400+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:05:56.398+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:05:56.400+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:05:56.468+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.090 seconds
[2025-02-11T07:06:27.061+0000] {processor.py:154} INFO - Started process (PID=268) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:06:27.063+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:06:27.065+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:06:27.065+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:06:27.077+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:06:27.075+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:06:27.079+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:06:27.155+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.102 seconds
[2025-02-11T07:06:57.996+0000] {processor.py:154} INFO - Started process (PID=295) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:06:57.997+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:06:57.999+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:06:57.998+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:06:58.007+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:06:58.005+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:06:58.009+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:06:58.073+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.083 seconds
[2025-02-11T07:07:28.853+0000] {processor.py:154} INFO - Started process (PID=320) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:07:28.856+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:07:28.859+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:07:28.859+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:07:28.867+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:07:28.866+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:07:28.868+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:07:28.910+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.065 seconds
[2025-02-11T07:07:59.517+0000] {processor.py:154} INFO - Started process (PID=345) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:07:59.521+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:07:59.524+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:07:59.523+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:07:59.536+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:07:59.533+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:07:59.537+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:07:59.588+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.082 seconds
[2025-02-11T07:08:29.656+0000] {processor.py:154} INFO - Started process (PID=376) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:08:29.659+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:08:29.660+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:08:29.660+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:08:29.667+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:08:29.666+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:08:29.669+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:08:29.719+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.071 seconds
[2025-02-11T07:09:00.046+0000] {processor.py:154} INFO - Started process (PID=401) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:09:00.049+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:09:00.058+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:09:00.058+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:09:00.088+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:09:00.085+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:09:00.091+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:09:00.155+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.123 seconds
[2025-02-11T07:09:30.569+0000] {processor.py:154} INFO - Started process (PID=434) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:09:30.574+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:09:30.577+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:09:30.577+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:09:30.586+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:09:30.585+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:09:30.587+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:09:30.644+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.084 seconds
[2025-02-11T07:10:00.881+0000] {processor.py:154} INFO - Started process (PID=461) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:10:00.883+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:10:00.884+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:10:00.884+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:10:00.893+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:10:00.891+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:10:00.896+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:10:00.952+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.079 seconds
[2025-02-11T07:10:31.118+0000] {processor.py:154} INFO - Started process (PID=485) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:10:31.120+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:10:31.122+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:10:31.121+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:10:31.131+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:10:31.130+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:10:31.133+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:10:31.202+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.092 seconds
[2025-02-11T07:11:02.069+0000] {processor.py:154} INFO - Started process (PID=509) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:11:02.071+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:11:02.072+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:11:02.072+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:11:02.081+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:11:02.080+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:11:02.083+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:11:02.132+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.070 seconds
[2025-02-11T07:11:32.368+0000] {processor.py:154} INFO - Started process (PID=543) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:11:32.370+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:11:32.373+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:11:32.372+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:11:32.381+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:11:32.379+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:11:32.383+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:11:32.431+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.070 seconds
[2025-02-11T07:12:02.485+0000] {processor.py:154} INFO - Started process (PID=567) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:12:02.488+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:12:02.490+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:12:02.490+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:12:02.502+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:12:02.499+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:12:02.503+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:12:02.578+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.103 seconds
[2025-02-11T07:12:32.639+0000] {processor.py:154} INFO - Started process (PID=592) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:12:32.642+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:12:32.643+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:12:32.643+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:12:32.653+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:12:32.650+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:12:32.655+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:12:32.701+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.068 seconds
[2025-02-11T07:13:02.822+0000] {processor.py:154} INFO - Started process (PID=617) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:13:02.824+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:13:02.827+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:13:02.827+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:13:02.838+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:13:02.835+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:13:02.839+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:13:02.886+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.072 seconds
[2025-02-11T07:13:33.542+0000] {processor.py:154} INFO - Started process (PID=650) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:13:33.549+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:13:33.552+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:13:33.552+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:13:33.577+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:13:33.575+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:13:33.580+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:13:33.701+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.174 seconds
[2025-02-11T07:14:04.027+0000] {processor.py:154} INFO - Started process (PID=674) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:14:04.030+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:14:04.031+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:14:04.031+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:14:04.041+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:14:04.039+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:14:04.043+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:14:04.114+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.095 seconds
[2025-02-11T07:14:34.728+0000] {processor.py:154} INFO - Started process (PID=699) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:14:34.729+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:14:34.731+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:14:34.731+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:14:34.741+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:14:34.739+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:14:34.746+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:14:34.828+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.110 seconds
[2025-02-11T07:15:05.008+0000] {processor.py:154} INFO - Started process (PID=724) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:15:05.011+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:15:05.012+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:15:05.012+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:15:05.021+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:15:05.019+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:15:05.022+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:15:05.076+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.074 seconds
[2025-02-11T07:15:35.190+0000] {processor.py:154} INFO - Started process (PID=750) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:15:35.193+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:15:35.196+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:15:35.196+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:15:35.207+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:15:35.205+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:15:35.208+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:15:35.254+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.070 seconds
[2025-02-11T07:16:05.320+0000] {processor.py:154} INFO - Started process (PID=784) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:16:05.324+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:16:05.326+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:16:05.326+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:16:05.334+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:16:05.333+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:16:05.336+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:16:05.388+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.077 seconds
[2025-02-11T07:16:35.464+0000] {processor.py:154} INFO - Started process (PID=809) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:16:35.466+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:16:35.467+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:16:35.467+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:16:35.477+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:16:35.474+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:16:35.478+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:16:35.529+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.075 seconds
[2025-02-11T07:17:05.873+0000] {processor.py:154} INFO - Started process (PID=833) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:17:05.876+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:17:05.878+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:17:05.877+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:17:05.885+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:17:05.883+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:17:05.889+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:17:05.930+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.064 seconds
[2025-02-11T07:17:35.999+0000] {processor.py:154} INFO - Started process (PID=868) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:17:36.000+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:17:36.002+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:17:36.002+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:17:36.009+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:17:36.008+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:17:36.010+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:17:36.067+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.075 seconds
[2025-02-11T07:18:06.499+0000] {processor.py:154} INFO - Started process (PID=892) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:18:06.501+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:18:06.503+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:18:06.503+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:18:06.526+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:18:06.524+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:18:06.529+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:18:06.580+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.088 seconds
[2025-02-11T07:18:36.901+0000] {processor.py:154} INFO - Started process (PID=916) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:18:36.904+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:18:36.906+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:18:36.906+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:18:36.916+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:18:36.914+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:18:36.917+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:18:36.962+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.067 seconds
[2025-02-11T07:19:07.134+0000] {processor.py:154} INFO - Started process (PID=941) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:19:07.137+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:19:07.144+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:19:07.143+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:19:07.153+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:19:07.150+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:19:07.154+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:19:07.197+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.070 seconds
[2025-02-11T07:19:37.356+0000] {processor.py:154} INFO - Started process (PID=975) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:19:37.358+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:19:37.362+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:19:37.361+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:19:37.385+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:19:37.382+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:19:37.388+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:19:37.478+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.142 seconds
[2025-02-11T07:20:07.990+0000] {processor.py:154} INFO - Started process (PID=1000) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:07.993+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:20:07.996+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:20:07.995+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:08.011+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:20:08.009+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:20:08.012+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:08.061+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.077 seconds
[2025-02-11T07:20:38.844+0000] {processor.py:154} INFO - Started process (PID=1025) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:38.845+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:20:38.847+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:20:38.847+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:38.854+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:20:38.853+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:20:38.855+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:38.898+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.060 seconds
[2025-02-11T07:20:56.662+0000] {processor.py:154} INFO - Started process (PID=1049) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:56.671+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:20:56.675+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:20:56.674+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:56.711+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:20:56.708+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:20:56.712+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:20:56.824+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.171 seconds
[2025-02-11T07:21:26.998+0000] {processor.py:154} INFO - Started process (PID=1074) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:21:26.999+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:21:27.001+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:21:27.000+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:21:27.007+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:21:27.006+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:21:27.009+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:21:27.049+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.064 seconds
[2025-02-11T07:21:57.092+0000] {processor.py:154} INFO - Started process (PID=1099) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:21:57.094+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:21:57.095+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:21:57.095+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:21:57.104+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:21:57.102+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:21:57.106+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:21:57.153+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.067 seconds
[2025-02-11T07:22:27.429+0000] {processor.py:154} INFO - Started process (PID=1124) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:22:27.431+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:22:27.433+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:22:27.432+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:22:27.442+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:22:27.440+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:22:27.443+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:22:27.493+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.071 seconds
[2025-02-11T07:22:57.864+0000] {processor.py:154} INFO - Started process (PID=1149) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:22:57.867+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:22:57.868+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:22:57.868+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:22:57.875+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:22:57.873+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:22:57.876+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:22:57.916+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.059 seconds
[2025-02-11T07:23:28.227+0000] {processor.py:154} INFO - Started process (PID=1183) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:23:28.229+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:23:28.231+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:28.230+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:23:28.239+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:28.237+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 33
    check_files = BashOperator(
    ^
IndentationError: unexpected indent
[2025-02-11T07:23:28.240+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:23:28.290+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.070 seconds
[2025-02-11T07:23:39.715+0000] {processor.py:154} INFO - Started process (PID=1193) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:23:39.718+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:23:39.719+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:39.719+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:23:39.814+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:23:40.536+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:40.535+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:23:40.591+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:40.590+0000] {dag.py:2606} INFO - Creating ORM DAG for group_dag.downloads
[2025-02-11T07:23:40.633+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:40.633+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T07:23:40.640+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:40.639+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:23:40.686+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:40.686+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:23:40.697+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:23:40.697+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:23:40.731+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.025 seconds
[2025-02-11T07:24:11.001+0000] {processor.py:154} INFO - Started process (PID=1218) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:24:11.003+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:24:11.013+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:11.012+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:24:11.135+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:24:11.754+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:11.754+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:24:11.831+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:11.831+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T07:24:11.840+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:11.840+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:24:11.855+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:11.855+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:24:11.872+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:11.871+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:24:11.914+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.920 seconds
[2025-02-11T07:24:42.232+0000] {processor.py:154} INFO - Started process (PID=1243) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:24:42.234+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:24:42.237+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:42.236+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:24:42.314+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:24:42.893+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:42.892+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:24:43.003+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:43.001+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T07:24:43.011+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:43.010+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:24:43.029+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:43.029+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:24:43.048+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:24:43.047+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:24:43.078+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.853 seconds
[2025-02-11T07:25:13.894+0000] {processor.py:154} INFO - Started process (PID=1267) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:25:13.895+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:25:13.896+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:13.896+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:25:13.981+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:25:14.525+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:14.524+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:25:14.612+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:14.612+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-10T00:00:00+00:00, run_after=2025-02-11T00:00:00+00:00
[2025-02-11T07:25:14.623+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:14.622+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:25:14.645+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:14.645+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:25:14.661+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:14.660+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:25:14.714+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.826 seconds
[2025-02-11T07:25:45.642+0000] {processor.py:154} INFO - Started process (PID=1304) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:25:45.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:25:45.660+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:45.652+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:25:45.918+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:25:46.782+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:46.782+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:25:46.871+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:46.871+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-11T00:00:00+00:00, run_after=2025-02-12T00:00:00+00:00
[2025-02-11T07:25:46.880+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:46.880+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:25:46.899+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:46.899+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:25:46.912+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:25:46.912+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:25:46.969+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.358 seconds
[2025-02-11T07:26:17.931+0000] {processor.py:154} INFO - Started process (PID=1327) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:26:17.933+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:26:17.935+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:17.935+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:26:18.042+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:26:18.635+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:18.634+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:26:18.771+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:18.771+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-11T00:00:00+00:00, run_after=2025-02-12T00:00:00+00:00
[2025-02-11T07:26:18.781+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:18.781+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:26:18.800+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:18.800+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:26:18.815+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:18.814+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:26:18.846+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.929 seconds
[2025-02-11T07:26:49.040+0000] {processor.py:154} INFO - Started process (PID=1352) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:26:49.047+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:26:49.052+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:49.051+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:26:49.439+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:26:50.006+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:50.006+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:26:50.251+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:50.251+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-11T00:00:00+00:00, run_after=2025-02-12T00:00:00+00:00
[2025-02-11T07:26:50.268+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:50.268+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:26:50.286+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:50.286+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:26:50.301+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:26:50.301+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:26:50.326+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.300 seconds
[2025-02-11T07:27:21.039+0000] {processor.py:154} INFO - Started process (PID=1377) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:27:21.040+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:27:21.041+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:21.041+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:27:21.130+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:27:21.516+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:21.516+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:27:21.570+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:21.569+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-11T00:00:00+00:00, run_after=2025-02-12T00:00:00+00:00
[2025-02-11T07:27:21.576+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:21.576+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:27:21.595+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:21.595+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:27:21.608+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:21.607+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:27:21.637+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.605 seconds
[2025-02-11T07:27:43.686+0000] {processor.py:154} INFO - Started process (PID=1401) to work on /opt/airflow/dags/group_dag.py
[2025-02-11T07:27:43.688+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2025-02-11T07:27:43.690+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:43.690+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2025-02-11T07:27:43.774+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2025-02-11T07:27:44.231+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:44.231+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2025-02-11T07:27:44.300+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:44.300+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2025-02-11T00:00:00+00:00, run_after=2025-02-12T00:00:00+00:00
[2025-02-11T07:27:44.308+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:44.308+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:27:44.324+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:44.324+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2025-02-11T07:27:44.335+0000] {logging_mixin.py:120} INFO - [2025-02-11T07:27:44.335+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2025-02-11T07:27:44.374+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.694 seconds
